-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 16:38:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acessos` (
  `AcessoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  PRIMARY KEY (`AcessoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partidos` (
  `PartidosID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Sigla` VARCHAR(20) NOT NULL,
  `N. legenda` INT(2) NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  PRIMARY KEY (`PartidosID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `TipoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  PRIMARY KEY (`TipoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleições`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleições` (
  `EleicaoID` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `HoraI` TIME NOT NULL,
  `HoraF` TIME NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  `Tipo_TipoID` INT NOT NULL,
  PRIMARY KEY (`EleicaoID`),
  INDEX `fk_eleições_Tipo1_idx` (`Tipo_TipoID` ASC) VISIBLE,
  CONSTRAINT `fk_eleições_Tipo1`
    FOREIGN KEY (`Tipo_TipoID`)
    REFERENCES `mydb`.`Tipo` (`TipoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `CargosID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  `Tipo_TipoID` INT NOT NULL,
  PRIMARY KEY (`CargosID`),
  INDEX `fk_cargos_Tipo1_idx` (`Tipo_TipoID` ASC) VISIBLE,
  CONSTRAINT `fk_cargos_Tipo1`
    FOREIGN KEY (`Tipo_TipoID`)
    REFERENCES `mydb`.`Tipo` (`TipoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`votocandidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`votocandidato` (
  `VotoCandidatoID` INT NOT NULL AUTO_INCREMENT,
  `DataHora` DATETIME(30) NOT NULL,
  `Presidente` VARCHAR(2) NOT NULL,
  `Governador` VARCHAR(2) NOT NULL,
  `Senador` VARCHAR(3) NOT NULL,
  `DepEstado` VARCHAR(5) NOT NULL,
  `DepFederal` VARCHAR(4) NOT NULL,
  `Secao` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `eleições_EleicaoID` INT NOT NULL,
  PRIMARY KEY (`VotoCandidatoID`),
  INDEX `fk_Voto_eleições1_idx` (`eleições_EleicaoID` ASC) VISIBLE,
  CONSTRAINT `fk_Voto_eleições1`
    FOREIGN KEY (`eleições_EleicaoID`)
    REFERENCES `mydb`.`eleições` (`EleicaoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidatos` (
  `CandidatoID` INT NOT NULL AUTO_INCREMENT,
  `NomeUrna` VARCHAR(150) NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(255) NOT NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL DEFAULT 'f',
  `partidos_PartidosID` INT NOT NULL,
  `cargos_CargosID` INT NOT NULL,
  `Voto_VotoID` INT NOT NULL,
  PRIMARY KEY (`CandidatoID`),
  INDEX `fk_candidatos_partidos1_idx` (`partidos_PartidosID` ASC) VISIBLE,
  INDEX `fk_candidatos_cargos1_idx` (`cargos_CargosID` ASC) VISIBLE,
  INDEX `fk_candidatos_Voto1_idx` (`Voto_VotoID` ASC) VISIBLE,
  CONSTRAINT `fk_candidatos_partidos1`
    FOREIGN KEY (`partidos_PartidosID`)
    REFERENCES `mydb`.`partidos` (`PartidosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidatos_cargos1`
    FOREIGN KEY (`cargos_CargosID`)
    REFERENCES `mydb`.`cargos` (`CargosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidatos_Voto1`
    FOREIGN KEY (`Voto_VotoID`)
    REFERENCES `mydb`.`votocandidato` (`VotoCandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidaturas` (
  `CandidaturaID` INT NOT NULL AUTO_INCREMENT,
  `eleições_EleicaoID` INT NOT NULL,
  `candidatos_CandidatoID` INT NOT NULL,
  PRIMARY KEY (`CandidaturaID`),
  INDEX `fk_candidaturas_eleições1_idx` (`eleições_EleicaoID` ASC) VISIBLE,
  INDEX `fk_candidaturas_candidatos1_idx` (`candidatos_CandidatoID` ASC) VISIBLE,
  CONSTRAINT `fk_candidaturas_eleições1`
    FOREIGN KEY (`eleições_EleicaoID`)
    REFERENCES `mydb`.`eleições` (`EleicaoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidaturas_candidatos1`
    FOREIGN KEY (`candidatos_CandidatoID`)
    REFERENCES `mydb`.`candidatos` (`CandidatoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `EstadosID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` CHAR(2) NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  PRIMARY KEY (`EstadosID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipios` (
  `MunicipiosID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` CHAR(2) NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  `estados_EstadosID` INT NOT NULL,
  PRIMARY KEY (`MunicipiosID`),
  INDEX `fk_municipios_estados1_idx` (`estados_EstadosID` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_EstadosID`)
    REFERENCES `mydb`.`estados` (`EstadosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zona` (
  `ZonaID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `estados_EstadosID` INT NOT NULL,
  `municipios_MunicipiosID` INT NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  PRIMARY KEY (`ZonaID`),
  INDEX `fk_zona_estados1_idx` (`estados_EstadosID` ASC) VISIBLE,
  INDEX `fk_zona_municipios1_idx` (`municipios_MunicipiosID` ASC) VISIBLE,
  CONSTRAINT `fk_zona_estados1`
    FOREIGN KEY (`estados_EstadosID`)
    REFERENCES `mydb`.`estados` (`EstadosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_municipios1`
    FOREIGN KEY (`municipios_MunicipiosID`)
    REFERENCES `mydb`.`municipios` (`MunicipiosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secao` (
  `SecaoID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Excluido` CHAR(1) NOT NULL,
  `estados_EstadosID` INT NOT NULL,
  `municipios_MunicipiosID` INT NOT NULL,
  PRIMARY KEY (`SecaoID`),
  INDEX `fk_secao_estados1_idx` (`estados_EstadosID` ASC) VISIBLE,
  INDEX `fk_secao_municipios1_idx` (`municipios_MunicipiosID` ASC) VISIBLE,
  CONSTRAINT `fk_secao_estados1`
    FOREIGN KEY (`estados_EstadosID`)
    REFERENCES `mydb`.`estados` (`EstadosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_secao_municipios1`
    FOREIGN KEY (`municipios_MunicipiosID`)
    REFERENCES `mydb`.`municipios` (`MunicipiosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eleitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eleitores` (
  `EleitoresID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EleitoresID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`votoeleitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`votoeleitor` (
  `VotoEleitorID` INT NOT NULL,
  `DataHora` DATETIME NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  `Secao` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VotoEleitorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`urna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`urna` (
  `UrnaID` INT NOT NULL AUTO_INCREMENT,
  `NIdentificacao` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  `Excluido` VARCHAR(1) NOT NULL,
  `Secao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UrnaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`importar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`importar` (
  `idimportar` INT NOT NULL AUTO_INCREMENT,
  `Urna` VARCHAR(45) NOT NULL,
  `Secao` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  `Arquivo` VARCHAR(300) NOT NULL,
  `DataHora` DATETIME NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `urna_UrnaID` INT NOT NULL,
  PRIMARY KEY (`idimportar`),
  INDEX `fk_importar_urna1_idx` (`urna_UrnaID` ASC) VISIBLE,
  CONSTRAINT `fk_importar_urna1`
    FOREIGN KEY (`urna_UrnaID`)
    REFERENCES `mydb`.`urna` (`UrnaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
